### ISSUE TITLE
.NET Standard dlls

### ISSUE THREAD

**Issue by Thieum** [biohazard999/DXNugetPackageBuilder#3]
Since 18.1, there are now .NET standard version of some of the dlls, located in C:\Program Files (x86)\DevExpress 18.1\Components\Bin\Standard

![image](https://user-images.githubusercontent.com/944894/43775797-ec166584-9a1b-11e8-8382-dbc724bcd4ce.png)

It would be nice to merge this dlls in the appropriate packages, and have a multi-target package as a result.

![image](https://user-images.githubusercontent.com/944894/43775928-5383f36c-9a1c-11e8-894a-9b1827ff7be6.png)

**Comment by biohazard999** [comment]
I thought already about this, but didn't Had time so far.
Any PR on this would be cool :)

**Comment by Thieum** [comment]
Another problem I hit after more tests is that `Assembly.LoadFile` will load the GAC version if it has been installed. Other versions of the loading like Assembly.Load / Assembly.LoadFrom have the same issue. I don't see anyway of doing the package and getting the right dependencies without doing it on a machine that has not the components installed through the DevExpress Installer.

I tried to call GacUtil to temporarily uninstall the dll from the GAC, but it didn't work, and I don't think it's a better idea anyway.

References:
https://stackoverflow.com/a/1607105/444469

**Comment by biohazard999** [comment]
Maybe I have an alternative idea.
In this [very old ticket](https://www.devexpress.com/Support/Center/Question/Details/Q458075/please-provide-nuget-packages) Serge was mentioning using the Assembly Deployment Tool's xml file.

I'm currently installing the latest DevExpress version and let's see if we can do something about it this way.
Another way is to provide different .NET exe's compiled against different versions (I would have done this if I ever needed Silverlight for example) and just serialize the dependency tree, and pack them afterwards. (That's what the analyzer was ment for)

But thanks for your PR anyways.
I think I will port this thing to the new csproj format and give it a shine, combined with the official nuget support. But that's the main reason I don't really maintain it anymore. Hoping official nuget support gets better and better over time.

**Comment by biohazard999** [comment]
For the assembly loading problem, I think there is a better way.
1. Point the installer to the tool and do a [silent install](https://documentation.devexpress.com/GeneralInformation/15656/Installation/Install-DevExpress-NET-Products/Silent-Install-Mode)
2. Copy over all DLL's in a temp folder
3. Do the magic on the dll's (maybe we need seperate exe's to do the dependency walk, or just trust on matching names)
4. *Optional* match up with the existing packages from DevExpress official nuget feed

**Comment by Thieum** [comment]
It works when porting the project to .NET Core, as .NET Core doesn't know about the GAC. It can be run on a computer with DevExpress installed and generate the packages like the previous version. Preparing another PR.

**Comment by Thieum** [comment]
Made a PR to ookii.commandline for a .net standard version, but the package is attached here if needed in the mean time.


[Ookii.CommandLine.3.0.0.nupkg.zip](https://github.com/biohazard999/DXNugetPackageBuilder/files/2311439/Ookii.CommandLine.3.0.0.nupkg.zip)
[Ookii.CommandLine.3.0.0.symbols.nupkg.zip](https://github.com/biohazard999/DXNugetPackageBuilder/files/2311440/Ookii.CommandLine.3.0.0.symbols.nupkg.zip)

**Comment by Thieum** [comment]
I guess we can close this as it seems to work fine :)
